Add missing py2.7 coding
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/build/geopy/geopy/setup.py", line 8, in <module>
    from geopy import __version__ as version
  File "geopy/__init__.py", line 12, in <module>
    from geopy.geocoders import *  # noqa
  File "geopy/geocoders/__init__.py", line 81
SyntaxError: Non-ASCII character '\xc3' in file geopy/geocoders/__init__.py on line 82, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details