tests: fix ArcGIS failing test_reverse_no_result
FAILED test/geocoders/arcgis.py::TestArcGIS::test_reverse_no_result - assert Location(, ,  , , (35.173809, -37.485351, 0.0)) is None