ArcGIS tests: remove failing `test_reverse_no_result`
______ TestArcGIS.test_reverse_no_result ________________
test/geocoders/arcgis.py:92: in test_reverse_no_result
    expect_failure=True
test/geocoders/util.py:143: in reverse_run
    assert result is None
E   assert Location(, ,  , ATA, (-84.172382, 45.9873073, 0.0)) is None