HERE: fix a typo: *è*xactly_one (which breaks py2)
Python 2 error message:

SyntaxError: Non-ASCII character '\xc3' in file
.../geopy/geocoders/here.py on line 135, but no encoding declared;
see http://www.python.org/peps/pep-0263.html for details.